version: "3.9" 
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=blog
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
  server:
    depends_on:
      - mongo
    build: .
    env_file: ./.env
    ports:
      - "4000:4000"